services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@1234
      - POSTGRES_DB=auditing
    ports:
      - "5432:5432"
    restart: always
    container_name: postgresdb
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./dump/:/var/postgres:rw
      - ./entrypoint/:/docker-entrypoint-initdb.d:rw

volumes:
  pg-data: